# Generated by Django 5.2.8 on 2025-12-09 14:36

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=160, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_workspaces', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='WorkspaceMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('member', 'Member')], default='member', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_memberships', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='core.workspace')),
            ],
        ),
        migrations.AddIndex(
            model_name='workspace',
            index=models.Index(fields=['slug'], name='core_worksp_slug_a852b9_idx'),
        ),
        migrations.AddIndex(
            model_name='workspace',
            index=models.Index(fields=['name'], name='core_worksp_name_eadf5f_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['workspace', 'name'], name='core_projec_workspa_310f22_idx'),
        ),
        migrations.AddIndex(
            model_name='workspacemembership',
            index=models.Index(fields=['workspace', 'user'], name='core_worksp_workspa_46a682_idx'),
        ),
        migrations.AddIndex(
            model_name='workspacemembership',
            index=models.Index(fields=['workspace', 'role'], name='core_worksp_workspa_a9e3d9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='workspacemembership',
            unique_together={('user', 'workspace')},
        ),
    ]
